- id: doc-cluster-apps
  name: Generate cluster app docs
  description: This hook generates a markdown-formatted documentation file for cluster applications installed in managed Kubernetes clusters.
  entry: hooks/doc-cluster-apps.sh
  language: script
  always_run: true
- id: doc-policies
  name: Generate policy docs
  description: This hook generates markdown-formatted documentation for Kubernetes policies
  entry: hooks/doc-policies.sh
  language: script
  always_run: true
- id: doc-crossplane-providers
  name: Document Crossplane provider versions
  description: This hook generates markdown-formatted documentation for Crossplane provider versions
  entry: hooks/doc-provider-versions.sh
  language: script
  always_run: true
